### --- Create session
# @name createSession

POST http://localhost:4004/api/admin/Sessions
Content-Type: application/json

{
  "numberRange": "2 - 3"
}


### --- Create assignment
# @name createAssignment

@sessionID = {{createSession.response.body.$.ID}}

POST http://localhost:4004/api/assign/SessionAssignments
Content-Type: application/json

{
  "session_ID": "{{sessionID}}"
}


### --- Get credentials for assignment
# @name getCredentials

@assignmentName = {{createAssignment.response.body.$.name}}

GET http://localhost:4004/api/assign/SessionAssignments(name='{{assignmentName}}',session_ID='{{sessionID}}')/credentials
Content-Type: application/json