###

POST http://localhost:4004/rest/assign/SessionAssignments
Content-Type: application/json

{
  "session_ID": "68824bc9-bddd-476a-8a30-65c147030a5b"
}


### get token for assignment

POST http://localhost:4004/rest/assign/SessionAssignments(name='foo3',session_ID=68824bc9-bddd-476a-8a30-65c147030a5b)/token
Content-Type: application/json